# Generated by Django 5.2.15 on 2026-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personwithdisability',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='ลิงก์ Google Maps'),
        ),
        migrations.AddField(
            model_name='personwithdisability',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='รูปถ่าย'),
        ),
    ]
