# Generated by Django 5.2.15 on 2026-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilities', '0002_personwithdisability_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personwithdisability',
            name='notes',
            field=models.TextField(blank=True, verbose_name='หมายเหตุ'),
        ),
    ]
