# Generated by Django 5.2.15 on 2026-06-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilities', '0003_personwithdisability_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personwithdisability',
            name='house_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='เลขที่'),
        ),
        migrations.AddField(
            model_name='personwithdisability',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='personwithdisability',
            name='road',
            field=models.CharField(blank=True, max_length=150, verbose_name='ถนน'),
        ),
        migrations.AddField(
            model_name='personwithdisability',
            name='village_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='หมู่บ้าน'),
        ),
        migrations.AddField(
            model_name='personwithdisability',
            name='village_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='หมู่ที่'),
        ),
    ]
