# Generated by Django 5.2.15 on 2026-06-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilities', '0004_personwithdisability_house_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_checks', to='disabilities.personwithdisability')),
            ],
            options={
                'ordering': ['-check_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCheckPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='check_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='disabilities.medicalcheck')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
