# Generated by Django 5.2.15 on 2026-06-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabilities', '0006_personwithdisability_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personwithdisability',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='ละติจูด'),
        ),
        migrations.AlterField(
            model_name='personwithdisability',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='ลองจิจูด'),
        ),
        migrations.AlterField(
            model_name='personwithdisability',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='ลิงก์ Google Maps'),
        ),
    ]
